version: '3.6'
services:
  haste-server:
    build: .
    image: hastepad:0.6
    ports:
      - 7777:7777
    volumes:
      - type: tmpfs
        target: /usr/src/app/data
        tmpfs:
          size: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

networks:
  db-network:
